language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
  - "11"
install:
  - npm install
  - npm run build
after_script:
  - "test -e ./coverage/lcov.info && cat ./coverage/lcov.info | node_modules/.bin/coveralls"
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
